"""Remote provisioning: clean-install the agent and/or sni-router over SSH.

Triggered by an authenticated UI user (Hosts → Remote install). SSH credentials
are passed per request and never persisted — see ssh.py. `provision()` is blocking
and is called from the endpoint via asyncio.to_thread.

Remote install is always a **clean install**: the agent installer runs with
`--purge` (wipes old dirs/config) and the router's config is wiped + rewritten,
so a fresh token/bind replaces whatever was there. In-dashboard version updates
(`sni-router-ui -u`, the agent's POST /update) take the opposite path and preserve
config. ponytail: the installer scripts hold the install logic — we just drive them.
"""
import os
import secrets

import db
import ssh

SCRIPTS = os.path.join(os.path.dirname(__file__), "..", "scripts")
SNI_INSTALL_URL = "https://raw.githubusercontent.com/Ashteeer/sni-router/main/install.sh"


def gen_token():
    return secrets.token_hex(24)


def rand_port():
    return 20000 + secrets.randbelow(40000)


def _sudo(user):
    return "" if (user or "root") == "root" else "sudo "


def _connect(s):
    return ssh.connect(
        host=s["host"], port=s.get("port", 22), user=s.get("user", "root"),
        password=s.get("password"), key=s.get("key"),
    )


def base_router_config(api_bind, api_port, token):
    """Minimal valid sni-router config: an API-only config (no listeners/backends)
    exposing the unified api (config + metrics + control) on an external interface
    with a token. The operator adds routing later in the Configs tab. config.md §1
    allows an API-only config; §8 = one bind, one token."""
    return f"""# Base config generated by SNI-Router UI provisioning.
# API-only — add listeners/backends in the Configs tab once the router is up.
api:
  bind: "{api_bind}:{api_port}"
  token: "{token}"
"""


def _install_agent(cl, sudo, bind, port, token, version):
    """Upload + run install-agent.sh with --purge (clean install). Returns log."""
    with open(os.path.join(SCRIPTS, "install-agent.sh"), encoding="utf-8") as f:
        script = f.read()
    ssh.put(cl, "/tmp/install-agent.sh", script)
    args = f"--purge -a {bind}:{port} -t {token}"
    if version:
        args += f" -v {version}"
    code, log = ssh.run(cl, f"{sudo}bash /tmp/install-agent.sh {args}; rm -f /tmp/install-agent.sh")
    if code != 0:
        raise RuntimeError(log.strip() or "agent install failed")
    return log


def _install_router(cl, sudo, api_bind, api_port, token, version):
    """Clean-install sni-router: run their install.sh, wipe any old config, then
    write a fresh API-only base config and start the service. Returns log."""
    code, log = ssh.run(cl, f"curl -fsSL {SNI_INSTALL_URL} | {sudo}bash", timeout=600)
    if code != 0:
        raise RuntimeError("sni-router install.sh failed:\n" + log.strip())
    # clean install: drop any pre-existing config before writing the fresh one
    ssh.run(cl, f"{sudo}rm -f /etc/sni-router/sni-router.yaml /etc/sni-router/sni-router.yml")
    cfg = base_router_config(api_bind, api_port, token)
    # service runs as User=sni-router; hand it a readable (0640, owned) config
    ssh.put_root(cl, sudo, "/etc/sni-router/sni-router.yaml", cfg, mode="0640")
    ssh.run(cl, f"{sudo}chown sni-router:sni-router /etc/sni-router/sni-router.yaml")
    code, log2 = ssh.run(cl, f"{sudo}systemctl enable --now sni-router")
    log += "\n" + log2
    if code != 0:
        raise RuntimeError("starting sni-router failed:\n" + log2.strip())
    return log


def provision(p):
    """Clean-install the selected targets on the remote host, then create or
    overwrite the host row. `targets` is any of 'agent', 'router'.

    On a fresh install a new token is generated and shared by both (agent reuses
    the router token via agent_token). When updating an existing host, only the
    fields for the installed targets are overwritten."""
    targets = [t for t in (p.get("targets") or []) if t in ("agent", "router")]
    if not targets:
        raise RuntimeError("no install target selected (agent / router)")

    s = p["ssh"]
    sudo = _sudo(s.get("user", "root"))
    version = (p.get("version") or "").strip()
    token = gen_token()  # fresh token — clean install overwrites the old one
    api_bind = p.get("api_bind") or "0.0.0.0"
    api_port = int(p.get("api_port") or 9901)
    agent_bind = p.get("agent_bind") or "0.0.0.0"
    agent_port = int(p.get("agent_port") or rand_port())
    agent_ip = (p.get("agent_ip") or "").strip()  # blank = reuse the router ip

    log = ""
    cl = _connect(s)
    try:
        if "router" in targets:
            log += _install_router(cl, sudo, api_bind, api_port, token, version)
        if "agent" in targets:
            log += ("\n" if log else "") + _install_agent(cl, sudo, agent_bind, agent_port, token, version)
    finally:
        cl.close()

    ip = s["host"]  # the reachable router-api IP (and the agent's, when blank)
    host_id = p.get("host_id")
    if host_id:
        fields = {"name": p.get("name") or s["host"], "ip": ip}
        if "router" in targets:
            fields.update(port=api_port, token=token)
        if "agent" in targets:
            fields.update(agent_ip=agent_ip, agent_port=agent_port, agent_token=token)
        db.update_host(host_id, **fields)
    else:
        host_id = db.add_host(
            p.get("name") or s["host"], ip, api_port,
            token=token, agent_ip=agent_ip, agent_port=agent_port, agent_token="",
        )
    return {"ok": True, "host_id": host_id, "targets": targets,
            "api_port": api_port if "router" in targets else None,
            "agent_ip": agent_ip or ip,
            "agent_port": agent_port if "agent" in targets else None,
            "token": token, "log": log}
