"""Remote provisioning: install the agent or sni-router on a host over SSH.

Triggered by an authenticated UI user (Hosts → Install …). SSH credentials are
passed per request and never persisted — see ssh.py. Each function is blocking
and is called from the endpoint via asyncio.to_thread.

ponytail: the agent installer script is uploaded and executed as-is (same
version as this site), so there's no second copy of the install logic here.
"""
import os
import secrets

import db
import ssh

SCRIPTS = os.path.join(os.path.dirname(__file__), "..", "scripts")
SNI_INSTALL_URL = "https://raw.githubusercontent.com/Ashteeer/sni-router/main/install.sh"


def gen_token():
    return secrets.token_hex(24)


def rand_port():
    return 20000 + secrets.randbelow(40000)


def _sudo(user):
    return "" if (user or "root") == "root" else "sudo "


def _connect(s):
    return ssh.connect(
        host=s["host"], port=s.get("port", 22), user=s.get("user", "root"),
        password=s.get("password"), key=s.get("key"),
    )


def provision_agent(p):
    """Upload + run scripts/install-agent.sh on the target, then record the host."""
    s = p["ssh"]
    user = s.get("user", "root")
    sudo = _sudo(user)
    token = p.get("token") or gen_token()
    bind = p.get("agent_bind") or "0.0.0.0"
    port = int(p.get("agent_port") or rand_port())
    version = (p.get("version") or "").strip()

    with open(os.path.join(SCRIPTS, "install-agent.sh"), encoding="utf-8") as f:
        script = f.read()

    cl = _connect(s)
    try:
        ssh.put(cl, "/tmp/install-agent.sh", script)
        args = f"-a {bind}:{port} -t {token}"
        if version:
            args += f" -v {version}"
        code, log = ssh.run(cl, f"{sudo}bash /tmp/install-agent.sh {args}; rm -f /tmp/install-agent.sh")
    finally:
        cl.close()
    if code != 0:
        raise RuntimeError(log.strip() or "agent install failed")

    host_id = p.get("host_id")
    if host_id:
        db.update_host(host_id, agent_port=port, token=token)
    else:
        host_id = db.add_host(
            p.get("name") or s["host"], s["host"], p.get("api_port", 9901),
            token=token, agent_port=port,
        )
    return {"ok": True, "host_id": host_id, "agent_port": port, "token": token, "log": log}


def base_router_config(api_bind, api_port, token):
    """Minimal valid sni-router config: an API-only config (no listeners/backends)
    exposing the unified api (config + metrics + control) on an external interface
    with a token. The operator adds routing later in the Configs tab. config.md §1
    allows an API-only config; §8 = one bind, one token."""
    return f"""# Base config generated by SNI-Router UI provisioning.
# API-only — add listeners/backends in the Configs tab once the router is up.
api:
  bind: "{api_bind}:{api_port}"
  token: "{token}"
"""


def provision_sni_router(p):
    """Install sni-router (their install.sh), drop a base config exposing the
    api (one bind, one token) on an external IP, then enable+start; record host."""
    s = p["ssh"]
    user = s.get("user", "root")
    sudo = _sudo(user)
    token = p.get("token") or gen_token()
    api_bind = p.get("api_bind") or p.get("admin_bind") or "0.0.0.0"
    api_port = int(p.get("api_port") or p.get("admin_port") or 9901)
    cfg = base_router_config(api_bind, api_port, token)

    cl = _connect(s)
    try:
        code, log = ssh.run(cl, f"curl -fsSL {SNI_INSTALL_URL} | {sudo}bash", timeout=600)
        if code != 0:
            raise RuntimeError("sni-router install.sh failed:\n" + log.strip())
        ssh.put_root(cl, sudo, "/etc/sni-router/sni-router.yaml", cfg, mode="0640")
        # The service runs as User=sni-router; a root:root 0600 config is unreadable
        # to it and the daemon exits with "Permission denied". Hand it to that user.
        ssh.run(cl, f"{sudo}chown sni-router:sni-router /etc/sni-router/sni-router.yaml")
        code, log2 = ssh.run(cl, f"{sudo}systemctl enable --now sni-router")
        log += "\n" + log2
        if code != 0:
            raise RuntimeError("starting sni-router failed:\n" + log2.strip())
    finally:
        cl.close()

    host_id = p.get("host_id")
    if host_id:
        db.update_host(host_id, port=api_port, token=token)
    else:
        host_id = db.add_host(
            p.get("name") or s["host"], s["host"], api_port,
            token=token, agent_port=p.get("agent_port", 9110),
        )
    return {"ok": True, "host_id": host_id, "api_port": api_port,
            "token": token, "log": log}
